version: '3.8'
services:
  mongodb:
    image: 'mongo'
    volumes:
      - data:/data/db
    #environment: 
      #MONGO_INITDB_ROOT_USERNAME: max
      #MONGO_INITDB_ROOT_PASSWORD: secret
    env_file:
      - ./env/mongo.env
    container_name: 'mongodb'  
   # networks:
   #   - goals-net
  backend:
    build: ./backend
    #build:
    #  context: ./backend
    #  dockerfile: Dockerfile
    #   args:
    ports:
      - '80:80'
    volumes:
      - logs:/app/logs
      - ./backend:/app
      - /app/node_modules
    env_file:
      - ./env/backend.env
    container_name: 'goals-backend'
    depends_on:
      - mongodb
    #networks:
    #  - goals-net
  frontend:
    build: ./frontend
    #build:
    #  context: ./frontend
    #  dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
    container_name: 'goals-frontend'
    depends_on:
      - backend
    #networks:
    #  - goals-net


volumes:
  data:
  logs:
